@if (have_rows('new_blocks'))
    @while (have_rows('new_blocks'))
        @php the_row() @endphp
        @include('partials/blocks/new-block-three-columns-icon')
        @include('partials/blocks/new-block-in-numbers')
        @include('partials/blocks/new-block-cta-full-bg-image')
        @include('partials/blocks/new-block-products-grid')
        @include('partials/blocks/new-block-in-page-links')
        @include('partials/blocks/pillar-page')
        @include('partials/blocks/new-block-case-study')
        @include('partials/blocks/new-block-image-gallery-slider')
        @include('partials/blocks/new-block-image-with-list')
        @include('partials/blocks/new-block-image-with-list-logos')
        @include('partials/blocks/new-block-icons-list')
        @include('partials/blocks/new-block-related-content')
        @include('partials/blocks/new-block-faq')
        @include('partials/blocks/new-block-faq-new-layout')
        @include('partials/blocks/new-block-form')
        @include('partials/blocks/new-block-manual-products-grid')
        @include('partials/blocks/new-block-big-cta')
        @include('partials/blocks/new-block-boxes')
        @include('partials/blocks/new-block-boxes-contact')
        @include('partials/blocks/new-block-header-subtext-btn')
        @include('partials/blocks/new-block-two-col-image')
        @include('partials/explorer/explorer')
    @endwhile
@endif
