@if (get_row_layout() == 'explorer')

<!-- jQuery (Ensure this is loaded first) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Maphilight and ImageMapResizer Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/maphilight/1.4.0/jquery.maphilight.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/image-map-resizer/1.0.10/js/imageMapResizer.min.js" defer></script>

<style>
    .modal-body {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 0;
    }

    .modal-body img {
        width: 100%;
        height: 100%;
        object-fit: contain;
        max-width: 100%;
        max-height: 100vh;
    }
</style>

<section class="block bg-casa-light pt-5" id="explorer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 p-0">
                @if (get_sub_field('header'))
                    <h2 class="pt-5 pb-3 text-center font-black">
                        @php the_sub_field('header') @endphp
                    </h2>
                @endif
                @if (get_sub_field('sub_header'))
                    <p class="pb-5 text-center">
                        @php the_sub_field('sub_header') @endphp
                    </p>
                @endif
                <div class="map-container">
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="@asset('images/explorer/orikum_bay_explorer_main_image.jpg')" usemap="#image-map" class="map" id="mainExplorerImage">

                    <map name="image-map">
                        <area target="" alt="Left Side Building" title="Left Side Building" href="#leftSideBuilding" coords="51,551,55,189,69,186,520,189,548,194,570,239,566,301,585,331,584,350,614,356,626,383,625,448,643,455,655,467,652,499,689,503,688,551" shape="poly">
                        <area target="" alt="Right Side Building" title="Right Side Building" href="#leftSideBuilding" coords="742,551,742,502,775,500,774,449,782,448,775,397,787,397,786,346,802,342,804,289,818,286,816,166,1345,72,1368,75,1384,76,1475,131,1471,552" shape="poly">
                    </map>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Fullscreen Modals -->
@foreach(['left' => 2926, 'right' => 2577] as $side => $id)
    @php
        $idExists = does_drawattention_id_exist($id);
    @endphp
    <div class="modal fade" id="{{ $side }}ModalWindow" tabindex="-1" aria-labelledby="{{ $side }}ModalWindowLabel" aria-hidden="true" style="background-color: #212721;">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content">
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-body">
                    @if ($idExists && shortcode_exists('drawattention'))
                        {!! do_shortcode("[drawattention ID=$id]") !!}
                    @else
                        <p class="text-center">Content not available.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endforeach

<script>
    jQuery(document).ready(function($) {
        // Function to handle area click
        function handleAreaClick(event, modalId) {
            event.preventDefault();
            $(modalId).modal('show').on('shown.bs.modal', function () {
                setTimeout(function() {
                    hotspots.init();
                }, 100);
            });
        }

        // Attach click handlers
        $('area[href="#leftModalWindow"]').on('click', function(event) { handleAreaClick(event, '#leftModalWindow'); });
        $('area[href="#rightModalWindow"]').on('click', function(event) { handleAreaClick(event, '#rightModalWindow'); });

        // Initialize Maphilight plugin
        $('#mainExplorerImage').maphilight({
            fillColor: '6f96d1',
            strokeColor: '000000',
        });

        // Initialize ImageMapResizer plugin
        $('map').imageMapResize();
    });
</script>

@endif
