@if (get_row_layout() == 'explorer')

<!-- jQuery (Ensure this is loaded first) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Maphilight and ImageMapResizer Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/maphilight/1.4.0/jquery.maphilight.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/image-map-resizer/1.0.10/js/imageMapResizer.min.js" defer></script>

<style>
    .modal-body {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 0;
    }

    .modal-body img {
        width: 100%;
        height: 100%;
        object-fit: contain;
        max-width: 100%;
        max-height: 100vh;
    }
</style>

<section class="block bg-casa-light pt-5" id="explorer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 p-0">
                @if (get_sub_field('header'))
                    <h2 class="pt-5 pb-3 text-center font-black">
                        @php the_sub_field('header') @endphp
                    </h2>
                @endif
                @if (get_sub_field('sub_header'))
                    <p class="pb-5 text-center">
                        @php the_sub_field('sub_header') @endphp
                    </p>
                @endif
                <div class="map-container">
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="@asset('images/explorer/orikum_bay_explorer_main_image.jpg')" usemap="#image-map" class="map" id="mainExplorerImage">

                    <map name="image-map">
                        <area target="" alt="Left" title="Left" href="#leftModalWindow" coords="18,454,31,479,75,527,118,567,153,592,193,616,239,638,327,646,379,640,396,635,381,613,374,591,392,578,414,570,457,557,503,541,581,508,637,483,695,443,734,414,773,398,837,390,858,390,846,362,832,327,826,290,821,257,804,230,784,212,754,182,742,153,730,131,713,123,676,139,613,187,595,206,552,225,511,250,460,274,400,306,139,401,86,416,31,441" shape="poly">
                        <area target="" alt="Middle" title="Middle" href="#centerModalWindow" coords="723,115,748,158,774,196,791,217,823,255,828,281,832,309,842,341,855,364,863,384,886,391,896,410,923,424,963,434,1007,446,1039,454,1076,472,1104,489,1138,507,1162,524,1192,529,1254,529,1316,529,1330,512,1259,483,1216,459,1201,432,1238,378,1278,335,1354,262,1430,184,1510,87,1503,71,1486,66,1390,63,1332,64,1271,69,1130,79,1072,85,996,87,942,88,826,93,753,106" shape="poly">
                        <area target="" alt="Right" title="Right" href="#rightModalWindow" coords="1333,515,1370,500,1405,499,1464,516,1516,530,1546,542,1575,548,1608,529,1688,472,1753,430,1780,411,1791,387,1686,343,1619,311,1680,255,1670,215,1600,192,1556,214,1526,238,1462,198,1492,163,1443,219,1398,256,1373,276,1352,300,1328,322,1311,345,1292,369,1278,378,1251,408,1239,424,1243,451,1255,467,1289,491" shape="poly">
                    </map>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Fullscreen Modals -->
@foreach(['left' => 1420, 'center' => 1418, 'right' => 1357] as $side => $id)
    @php
        $idExists = does_drawattention_id_exist($id);
    @endphp
    <div class="modal fade" id="{{ $side }}ModalWindow" tabindex="-1" aria-labelledby="{{ $side }}ModalWindowLabel" aria-hidden="true" style="background-color: #212721;">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content">
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-body">
                    @if ($idExists && shortcode_exists('drawattention'))
                        {!! do_shortcode("[drawattention ID=$id]") !!}
                    @else
                        <p class="text-center">Content not available.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endforeach

<script>
    jQuery(document).ready(function($) {
        // Function to handle area click
        function handleAreaClick(event, modalId) {
            event.preventDefault();
            $(modalId).modal('show').on('shown.bs.modal', function () {
                setTimeout(function() {
                    hotspots.init();
                }, 100);
            });
        }

        // Attach click handlers
        $('area[href="#leftModalWindow"]').on('click', function(event) { handleAreaClick(event, '#leftModalWindow'); });
        $('area[href="#centerModalWindow"]').on('click', function(event) { handleAreaClick(event, '#centerModalWindow'); });
        $('area[href="#rightModalWindow"]').on('click', function(event) { handleAreaClick(event, '#rightModalWindow'); });

        // Initialize Maphilight plugin
        $('#mainExplorerImage').maphilight({
            fillColor: '6f96d1',
            strokeColor: '000000',
        });

        // Initialize ImageMapResizer plugin
        $('map').imageMapResize();
    });
</script>

@endif
